import type { Package } from "@/lib/types";
import { photo } from "@/lib/images";

/** Season curves, Jan→Dec. 1.0 is the shoulder benchmark for that destination. */
const SEASON = {
  himalayaSummer: [0, 0, 0, 0.92, 1.0, 1.14, 1.28, 1.26, 1.08, 0.94, 0, 0],
  himalayaSpring: [0.86, 0.88, 1.12, 1.22, 1.1, 0.92, 0.86, 0.86, 1.06, 1.24, 1.08, 0.9],
  tropicalWinter: [1.28, 1.2, 1.06, 0.94, 0.84, 0.8, 0.86, 0.9, 0.86, 0.94, 1.12, 1.42],
  indiaWinter: [1.22, 1.16, 1.0, 0.9, 0.84, 0.82, 0.88, 0.9, 0.94, 1.06, 1.18, 1.34],
  archipelago: [1.16, 1.1, 1.0, 0.96, 0.94, 1.06, 1.18, 1.2, 1.04, 0.98, 1.0, 1.24],
  desertWinter: [1.14, 1.18, 1.06, 0.92, 0.78, 0.7, 0.7, 0.72, 0.84, 1.0, 1.16, 1.26],
  migration: [0.92, 0.98, 0.84, 0.78, 0.84, 1.12, 1.38, 1.44, 1.26, 1.0, 0.9, 1.1],
  mediterranean: [0, 0, 0, 0.9, 1.06, 1.2, 1.34, 1.38, 1.16, 0.94, 0, 0],
  andes: [0.86, 0.82, 0.9, 1.02, 1.14, 1.2, 1.26, 1.22, 1.08, 1.0, 0.94, 0.88],
};

export const PACKAGES: Package[] = [
  {
    slug: "ladakh-high-passes",
    name: "The High Passes of Ladakh",
    tagline: "Nine days above four thousand metres",
    destination: "Ladakh",
    country: "India",
    region: "himalaya",
    tripTypes: ["adventure", "culture"],
    nights: 8,
    baseAdultINR: 168000,
    fixedPerTravellerINR: 22000,
    rating: 4.9,
    reviewCount: 84,
    hero: photo("1506905925346-21bda4d32df4", 2000),
    gallery: [
      { src: photo("1506905925346-21bda4d32df4", 1200), caption: "Pangong Tso at first light" },
      { src: photo("1476514525535-07fb3b4ae5f1", 1200), caption: "The road to Khardung La" },
      { src: photo("1470071459604-3b5ec3a7fe05", 1200), caption: "Monastery cloud, Nubra" },
      { src: photo("1493246507139-91e8fad9978e", 1200), caption: "Camp above the Shyok" },
      { src: photo("1439066615861-d1af74d74000", 1200), caption: "Prayer flags, Chang La" },
    ],
    summary:
      "A slow, properly acclimatised crossing of Ladakh's three great valleys — Indus, Nubra and Changthang — staying in restored Ladakhi houses rather than hotels, with a Buddhist scholar travelling alongside you.",
    editorsNote:
      "We deliberately spend the first two nights doing almost nothing. Ladakh punishes itineraries that rush the altitude, and the whole trip is better for the patience.",
    highlights: [
      "Two nights on the shore of Pangong Tso with no other property in sight",
      "Private morning prayers at Thiksey before the monastery opens",
      "Dinner with a Changpa herding family on the Changthang plateau",
      "Khardung La and Chang La crossed on separate days, never back to back",
    ],
    itinerary: [
      { day: 1, title: "Arrive Leh — do nothing, deliberately", place: "Leh", description: "Met at Kushok Bakula airport and driven twenty minutes to a restored Ladakhi merchant's house. The rest of the day is horizontal: oxygen readings, apricot tea, a doctor's check at 6pm.", stay: "Stok Palace Residence", meals: ["Lunch", "Dinner"], highlight: "In-house physician reviews every traveller before the trip goes higher." },
      { day: 2, title: "Leh's old town, on foot", place: "Leh", description: "A gentle acclimatisation walk through the old bazaar, the Jama Masjid, and up to Namgyal Tsemo for sunset. Total ascent under 200 metres by design.", stay: "Stok Palace Residence", meals: ["Breakfast", "Dinner"] },
      { day: 3, title: "Thiksey before the gates open", place: "Indus Valley", description: "A 5:40am departure for the morning prayer assembly at Thiksey, then Hemis and Stakna along the Indus. Afternoon free.", stay: "Stok Palace Residence", meals: ["Breakfast", "Lunch"], highlight: "Private access to the Thiksey prayer hall an hour before public opening." },
      { day: 4, title: "Over Khardung La into Nubra", place: "Nubra Valley", description: "The high crossing at 5,359m — brief, monitored, and downhill quickly. Into the Nubra sand dunes by afternoon, camel-free and quiet.", stay: "Lchang Nang Retreat", meals: ["Breakfast", "Lunch", "Dinner"] },
      { day: 5, title: "Turtuk, the last village", place: "Turtuk", description: "Three hours west along the Shyok to a Balti village that only opened to visitors in 2010. Lunch cooked in a family kitchen; walnut orchards; the Pakistan border ridge in view.", stay: "Lchang Nang Retreat", meals: ["Breakfast", "Lunch", "Dinner"], highlight: "Lunch with a Balti family in Turtuk's upper village." },
      { day: 6, title: "The Shyok road to Pangong", place: "Pangong Tso", description: "A long, spectacular transfer along the river bed to the lake. Arrive mid-afternoon for the light.", stay: "Pangong Camp (private tents)", meals: ["Breakfast", "Lunch", "Dinner"] },
      { day: 7, title: "Pangong, unhurried", place: "Pangong Tso", description: "Sunrise on the water, a walk to Merak, and an astronomer-guided night sky session. The lake changes colour perhaps nine times in a day.", stay: "Pangong Camp (private tents)", meals: ["Breakfast", "Lunch", "Dinner"], highlight: "Guided astronomy on one of the darkest skies in inhabited India." },
      { day: 8, title: "Changthang and back over Chang La", place: "Leh", description: "Tea with a Changpa herding family among the pashmina goats, then the return crossing at Chang La and down into Leh.", stay: "Stok Palace Residence", meals: ["Breakfast", "Lunch", "Dinner"] },
      { day: 9, title: "Depart Leh", place: "Leh", description: "Early transfer to the airport. Most travellers connect through Delhi by mid-morning.", stay: "—", meals: ["Breakfast"] },
    ],
    inclusions: [
      "8 nights in restored heritage houses and private camps",
      "All internal ground transport in 4x4 Innova Crysta, one vehicle per 3 guests",
      "Resident Buddhist scholar and a certified high-altitude guide throughout",
      "Inner Line Permits for Nubra, Pangong and Changthang",
      "Arrival medical check and portable oxygen in every vehicle",
      "All meals as listed, including the Turtuk and Changthang family meals",
    ],
    exclusions: [
      "International and domestic flights to Leh",
      "Travel insurance (mandatory — we will not depart without it)",
      "Alcohol beyond the welcome dinner",
      "Camera fees at monasteries (₹100–₹300 each)",
      "Gratuities for guides and drivers",
    ],
    route: [
      { name: "Leh", x: 46, y: 58, nights: 3, arriveDay: 1 },
      { name: "Nubra Valley", x: 38, y: 28, nights: 2, arriveDay: 4 },
      { name: "Turtuk", x: 16, y: 22, nights: 0, arriveDay: 5 },
      { name: "Pangong Tso", x: 82, y: 46, nights: 2, arriveDay: 6 },
      { name: "Changthang", x: 70, y: 74, nights: 1, arriveDay: 8 },
    ],
    rooms: [
      { id: "heritage-double", name: "Heritage Double", description: "Original Ladakhi rooms in the Stok residence, wood-panelled, garden-facing.", multiplier: 1, maxAdults: 2 },
      { id: "courtyard-suite", name: "Courtyard Suite", description: "Corner suite with a private sit-out over the apricot courtyard and a separate reading room.", multiplier: 1.24, maxAdults: 3 },
      { id: "private-camp", name: "Private Camp Upgrade", description: "Your own dedicated Pangong camp cluster with a private dining tent and chef.", multiplier: 1.46, maxAdults: 4 },
    ],
    addOns: [
      { id: "chadar-photo", name: "Photography mentor", description: "A landscape photographer travels with your group for the Nubra and Pangong legs.", price: 46000, unit: "per-booking", recommended: true },
      { id: "heli-transfer", name: "Helicopter return from Nubra", description: "Skip the Khardung La return leg — 35 minutes instead of six hours.", price: 62000, unit: "per-traveller" },
      { id: "rafting", name: "Zanskar rafting morning", description: "Grade II–III on the Zanskar from Chilling to Nimmu, with a safety kayaker.", price: 8500, unit: "per-traveller" },
      { id: "oxygen-concentrator", name: "In-room oxygen concentrator", description: "A medical-grade concentrator in your room for every night above 3,000m.", price: 12000, unit: "per-booking" },
    ],
    seasonality: SEASON.himalayaSummer,
    groupSizeMax: 12,
    physicality: "Active",
  },
  {
    slug: "bhutan-thunder-dragon",
    name: "Bhutan: Valleys of the Thunder Dragon",
    tagline: "Paro, Thimphu and the Phobjikha crane valley",
    destination: "Western Bhutan",
    country: "Bhutan",
    region: "himalaya",
    tripTypes: ["wellness", "culture", "honeymoon"],
    nights: 7,
    baseAdultINR: 226000,
    fixedPerTravellerINR: 38000,
    rating: 4.8,
    reviewCount: 61,
    hero: photo("1470071459604-3b5ec3a7fe05", 2000),
    gallery: [
      { src: photo("1470071459604-3b5ec3a7fe05", 1200), caption: "Cloud over the Paro valley" },
      { src: photo("1439066615861-d1af74d74000", 1200), caption: "The climb to Taktsang" },
      { src: photo("1501785888041-af3ef285b470", 1200), caption: "Phobjikha at dusk" },
      { src: photo("1465101162946-4377e57745c3", 1200), caption: "Dzong courtyard, Punakha" },
    ],
    summary:
      "Seven nights across Bhutan's western valleys at an unhurried pace — two dzongs, one farmhouse hot-stone bath, the Tiger's Nest climb done properly at dawn, and three nights in the Phobjikha valley where the black-necked cranes winter.",
    editorsNote:
      "Almost everyone does Bhutan in five nights and spends two of them in a car. The extra two nights in Phobjikha are the entire point of this itinerary.",
    highlights: [
      "Taktsang (Tiger's Nest) climbed at 6am, before the day-trip crowds",
      "Three nights in Phobjikha — crane season runs late October to February",
      "A private blessing at Punakha Dzong with a resident lama",
      "Traditional hot-stone bath in a working Paro farmhouse",
    ],
    itinerary: [
      { day: 1, title: "The Paro approach", place: "Paro", description: "One of the great landings in aviation — the descent between ridgelines into Paro. Afternoon at Kyichu Lhakhang, Bhutan's oldest temple.", stay: "Amankora Paro", meals: ["Lunch", "Dinner"] },
      { day: 2, title: "Taktsang at dawn", place: "Paro", description: "A 6am start for the Tiger's Nest — 900m of ascent over roughly three hours, with a cafeteria halt. Down by early afternoon, then a hot-stone bath.", stay: "Amankora Paro", meals: ["Breakfast", "Lunch", "Dinner"], highlight: "On the trail before the day-visitor buses arrive from Thimphu." },
      { day: 3, title: "Thimphu, at working pace", place: "Thimphu", description: "The National Textile Academy, the weekend market if the day allows, and an archery match with a local club.", stay: "Six Senses Thimphu", meals: ["Breakfast", "Dinner"] },
      { day: 4, title: "Over Dochu La to Punakha", place: "Punakha", description: "The pass at 3,100m with its 108 chortens, then a long descent into the warm Punakha valley. Afternoon at the dzong at the river confluence.", stay: "Six Senses Punakha", meals: ["Breakfast", "Lunch", "Dinner"], highlight: "A private blessing in the Punakha Dzong's inner courtyard." },
      { day: 5, title: "Into the crane valley", place: "Phobjikha", description: "Three hours east and up into the glacial bowl of Phobjikha — no high-rise, no billboards, barely any tarmac.", stay: "Gangtey Lodge", meals: ["Breakfast", "Lunch", "Dinner"] },
      { day: 6, title: "Gangtey nature trail", place: "Phobjikha", description: "A four-hour walk from Gangtey Goenpa down through the valley floor, with the crane centre in the afternoon.", stay: "Gangtey Lodge", meals: ["Breakfast", "Lunch", "Dinner"] },
      { day: 7, title: "Return west", place: "Paro", description: "The long drive back to Paro, broken at Chimi Lhakhang and a riverside lunch.", stay: "Amankora Paro", meals: ["Breakfast", "Lunch", "Dinner"] },
      { day: 8, title: "Depart Paro", place: "Paro", description: "Morning departure. Drukair connects to Delhi, Kathmandu, Bangkok and Singapore.", stay: "—", meals: ["Breakfast"] },
    ],
    inclusions: [
      "7 nights at Amankora, Six Senses and Gangtey Lodge",
      "Bhutan Sustainable Development Fee for all nights",
      "Bhutan visa processing and permits",
      "Private guide and vehicle throughout",
      "All meals, and one hot-stone bath per traveller",
    ],
    exclusions: [
      "Flights to and from Paro",
      "Travel insurance",
      "Spa treatments beyond the included hot-stone bath",
      "Gratuities",
    ],
    route: [
      { name: "Paro", x: 18, y: 44, nights: 3, arriveDay: 1 },
      { name: "Thimphu", x: 38, y: 52, nights: 1, arriveDay: 3 },
      { name: "Punakha", x: 58, y: 36, nights: 1, arriveDay: 4 },
      { name: "Phobjikha", x: 82, y: 60, nights: 2, arriveDay: 5 },
    ],
    rooms: [
      { id: "lodge-suite", name: "Lodge Suite", description: "The standard room category across all three lodges — generous, valley-facing, wood and stone.", multiplier: 1, maxAdults: 2 },
      { id: "villa", name: "One-Bedroom Villa", description: "Private villa with an outdoor bath and a dedicated butler at each property.", multiplier: 1.38, maxAdults: 2 },
      { id: "family-villa", name: "Two-Bedroom Villa", description: "Connected villas with a shared living room — the sensible choice for four travelling together.", multiplier: 1.72, maxAdults: 4 },
    ],
    addOns: [
      { id: "textile-day", name: "Textile studio day", description: "A full day with a master weaver in Thimphu, working on a kira panel of your own.", price: 34000, unit: "per-traveller", recommended: true },
      { id: "heli-phobjikha", name: "Helicopter to Phobjikha", description: "Replace the three-hour road transfer with a 25-minute flight over the Black Mountains.", price: 148000, unit: "per-booking" },
      { id: "meditation", name: "Two-night monastery retreat", description: "Silent stay with a resident monk, replacing two lodge nights.", price: 0, unit: "per-traveller" },
      { id: "mountain-bike", name: "Punakha valley cycling", description: "Half-day on gravel through the rice terraces, bikes and support vehicle included.", price: 11500, unit: "per-traveller" },
    ],
    seasonality: SEASON.himalayaSpring,
    groupSizeMax: 8,
    physicality: "Moderate",
  },
  {
    slug: "maldives-atoll-solitude",
    name: "Maldives — Atoll Solitude",
    tagline: "Six nights, two atolls, no crossings after dark",
    destination: "Baa & Noonu Atolls",
    country: "Maldives",
    region: "indian-ocean",
    tripTypes: ["honeymoon", "wellness"],
    nights: 5,
    baseAdultINR: 284000,
    fixedPerTravellerINR: 44000,
    rating: 4.9,
    reviewCount: 128,
    hero: photo("1507525428034-b723cf961d3e", 2000),
    gallery: [
      { src: photo("1507525428034-b723cf961d3e", 1200), caption: "The lagoon at Baa" },
      { src: photo("1519046904884-53103b34b206", 1200), caption: "Sandbank breakfast" },
      { src: photo("1505881502353-a1986add3762", 1200), caption: "Overwater, late afternoon" },
      { src: photo("1544551763-46a013bb70d5", 1200), caption: "Hanifaru manta aggregation" },
    ],
    summary:
      "A two-atoll Maldives that resists the single-island trap: three nights on a Baa Atoll house reef inside a UNESCO biosphere, two on a quieter Noonu island, connected by a private seaplane leg timed for the light.",
    editorsNote:
      "The Hanifaru Bay manta aggregation only happens on specific lunar tides between June and October. We build the dates around the moon, not the other way round.",
    highlights: [
      "Snorkelling Hanifaru Bay in season — mantas by the dozen, no scuba permitted",
      "A private sandbank dinner, set up and struck the same evening",
      "Two-atoll structure so you never spend five days on one beach",
      "Marine biologist briefing before every water outing",
    ],
    itinerary: [
      { day: 1, title: "Malé and the seaplane north", place: "Baa Atoll", description: "Met airside at Velana, through the lounge, and onto a 30-minute seaplane to Baa. In the water within the hour.", stay: "Baa Atoll house reef villa", meals: ["Lunch", "Dinner"] },
      { day: 2, title: "The house reef, properly", place: "Baa Atoll", description: "Two guided snorkel sessions with the resident marine biologist — the reef drop-off at dawn, the coral nursery in the afternoon.", stay: "Baa Atoll house reef villa", meals: ["Breakfast", "Lunch", "Dinner"] },
      { day: 3, title: "Hanifaru Bay", place: "Hanifaru", description: "A ranger-permitted window at the bay when the tide is right, then an afternoon that is entirely yours.", stay: "Baa Atoll house reef villa", meals: ["Breakfast", "Lunch", "Dinner"], highlight: "Ranger-permitted Hanifaru access — capped at a fixed number of swimmers per slot." },
      { day: 4, title: "North to Noonu", place: "Noonu Atoll", description: "A short seaplane hop to a quieter island with a wider lagoon. Sunset dhoni cruise with a line and a bucket.", stay: "Noonu overwater villa", meals: ["Breakfast", "Lunch", "Dinner"] },
      { day: 5, title: "Sandbank day", place: "Noonu Atoll", description: "Dropped on a sandbank with a hamper, an umbrella and a radio. Collected when you call. Dinner back on the island, or on the sand if you prefer.", stay: "Noonu overwater villa", meals: ["Breakfast", "Lunch", "Dinner"], highlight: "Private sandbank with nothing on it but your own shade." },
      { day: 6, title: "Depart", place: "Malé", description: "Seaplane to Velana with time in the lounge before international connections.", stay: "—", meals: ["Breakfast"] },
    ],
    inclusions: [
      "5 nights in house-reef and overwater villas across two atolls",
      "All seaplane transfers, including the inter-atoll leg",
      "Full board with a daily beverage allowance",
      "All guided snorkelling with a resident marine biologist",
      "One private sandbank experience per booking",
    ],
    exclusions: [
      "International flights to Malé",
      "Scuba diving and certification courses",
      "Spa treatments",
      "Premium wines and spirits above the house list",
      "Green tax and TGST, quoted separately at booking",
    ],
    route: [
      { name: "Malé", x: 52, y: 84, nights: 0, arriveDay: 1 },
      { name: "Baa Atoll", x: 28, y: 44, nights: 3, arriveDay: 1 },
      { name: "Hanifaru", x: 40, y: 34, nights: 0, arriveDay: 3 },
      { name: "Noonu Atoll", x: 68, y: 22, nights: 2, arriveDay: 4 },
    ],
    rooms: [
      { id: "beach-villa", name: "Beach Villa with Pool", description: "Sand-floor villa opening directly onto the house reef beach, private plunge pool.", multiplier: 1, maxAdults: 2 },
      { id: "overwater", name: "Overwater Villa", description: "Lagoon-side with steps into the water and an outdoor bath. Both islands.", multiplier: 1.32, maxAdults: 2 },
      { id: "residence", name: "Two-Bedroom Residence", description: "Private stretch of beach, two bedrooms, a 15m pool and a dedicated chef.", multiplier: 2.05, maxAdults: 4 },
    ],
    addOns: [
      { id: "manta-charter", name: "Private manta charter", description: "Your own boat and biologist for the Hanifaru window rather than a shared slot.", price: 96000, unit: "per-booking", recommended: true },
      { id: "spa-journey", name: "Three-treatment spa journey", description: "A structured sequence over three days rather than one-off treatments.", price: 52000, unit: "per-traveller" },
      { id: "padi", name: "PADI Open Water course", description: "Four-day certification with the island dive centre, equipment included.", price: 68000, unit: "per-traveller" },
      { id: "photographer", name: "Underwater photographer", description: "A half-day shoot in the lagoon, edited gallery delivered within a week.", price: 74000, unit: "per-booking" },
    ],
    seasonality: SEASON.tropicalWinter,
    groupSizeMax: 6,
    physicality: "Gentle",
  },
  {
    slug: "kerala-backwaters-cardamom",
    name: "Kerala: Backwaters & Cardamom Hills",
    tagline: "Fort Kochi, Thekkady, and a houseboat that actually moves",
    destination: "Kerala",
    country: "India",
    region: "indian-ocean",
    tripTypes: ["family", "wellness", "culture"],
    nights: 6,
    baseAdultINR: 118000,
    fixedPerTravellerINR: 14000,
    rating: 4.7,
    reviewCount: 156,
    hero: photo("1602216056096-3b40cc0c9944", 2000),
    gallery: [
      { src: photo("1602216056096-3b40cc0c9944", 1200), caption: "Chinese nets, Fort Kochi" },
      { src: photo("1593693411515-c20261bcad6e", 1200), caption: "Backwater channel at dusk" },
      { src: photo("1580889240912-c39ecefd3d95", 1200), caption: "Cardamom drying, Thekkady" },
      { src: photo("1544984243-ec57ea16fe25", 1200), caption: "Kathakali, before the paint" },
    ],
    summary:
      "Six nights from the Arabian Sea up into the cardamom hills and back down to the backwaters — Dutch colonial Kochi, a working spice estate, and a private kettuvallam that cruises the narrow channels most boats are too wide for.",
    editorsNote:
      "Most Kerala houseboats spend the night moored in a car park of other houseboats. Ours is a 60-foot restored kettuvallam that anchors alone in a side channel.",
    highlights: [
      "A private, genuinely cruising houseboat — not a moored floating hotel",
      "Kathakali make-up room access two hours before the performance",
      "Two nights on a working cardamom and pepper estate",
      "Toddy-tapper's breakfast on the Vembanad shore",
    ],
    itinerary: [
      { day: 1, title: "Fort Kochi", place: "Kochi", description: "Arrive into Cochin and cross to the peninsula. Evening walk past the Chinese nets, St Francis Church and the Jew Town godowns.", stay: "Malabar House", meals: ["Dinner"] },
      { day: 2, title: "Kochi's layers", place: "Kochi", description: "Morning with a historian on the Portuguese-Dutch-British sequence, an afternoon at the Biennale spaces, and Kathakali in the evening — backstage first.", stay: "Malabar House", meals: ["Breakfast", "Dinner"], highlight: "Into the Kathakali make-up room while the artists are still applying the chutti." },
      { day: 3, title: "Up to the cardamom hills", place: "Thekkady", description: "Four hours climbing through rubber, then tea, then cardamom. Afternoon on the estate with the planter.", stay: "Spice Village estate cottage", meals: ["Breakfast", "Lunch", "Dinner"] },
      { day: 4, title: "Periyar at dawn", place: "Thekkady", description: "A bamboo raft on the Periyar lake at first light with a forest ranger, then a spice-trail walk and a cooking session.", stay: "Spice Village estate cottage", meals: ["Breakfast", "Lunch", "Dinner"], highlight: "Ranger-led bamboo rafting inside the reserve, before general entry." },
      { day: 5, title: "Down to the water", place: "Vembanad", description: "The descent to Kumarakom and onto your kettuvallam by early afternoon. The boat cruises until dusk, then anchors in a side channel.", stay: "Private kettuvallam", meals: ["Breakfast", "Lunch", "Dinner"] },
      { day: 6, title: "Backwater morning, lakeside evening", place: "Vembanad", description: "A canoe through the narrow canals at 6am, breakfast with a toddy tapper, then off the boat and into a lakeside villa.", stay: "Vembanad lake villa", meals: ["Breakfast", "Lunch", "Dinner"] },
      { day: 7, title: "Depart Kochi", place: "Kochi", description: "A ninety-minute transfer to Cochin airport.", stay: "—", meals: ["Breakfast"] },
    ],
    inclusions: [
      "6 nights across heritage hotel, estate cottage, private houseboat and lake villa",
      "Private air-conditioned vehicle with driver for all land transfers",
      "Historian in Kochi, planter in Thekkady, ranger at Periyar",
      "Full board on the houseboat, breakfast and dinner elsewhere",
      "Kathakali tickets with backstage access",
    ],
    exclusions: [
      "Flights to and from Cochin",
      "Ayurvedic treatments",
      "Lunches in Kochi",
      "Camera fees inside Periyar Tiger Reserve",
    ],
    route: [
      { name: "Kochi", x: 16, y: 40, nights: 2, arriveDay: 1 },
      { name: "Thekkady", x: 76, y: 30, nights: 2, arriveDay: 3 },
      { name: "Vembanad", x: 40, y: 68, nights: 1, arriveDay: 5 },
      { name: "Kumarakom", x: 32, y: 80, nights: 1, arriveDay: 6 },
    ],
    rooms: [
      { id: "heritage", name: "Heritage Room", description: "Colonial-era rooms in Fort Kochi, estate cottages in the hills.", multiplier: 1, maxAdults: 2 },
      { id: "pool-villa", name: "Pool Villa", description: "Private plunge pool at each property, upgraded houseboat cabin.", multiplier: 1.28, maxAdults: 3 },
      { id: "family-suite", name: "Family Suite", description: "Two connected bedrooms throughout, and the full two-cabin houseboat to yourselves.", multiplier: 1.55, maxAdults: 4 },
    ],
    addOns: [
      { id: "ayurveda", name: "Ayurvedic consultation & treatments", description: "A doctor's consultation and three prescribed treatments across the trip.", price: 22000, unit: "per-traveller", recommended: true },
      { id: "cooking", name: "Syrian Christian kitchen day", description: "A full day cooking in a family home in Kottayam — appam, meen curry, duck roast.", price: 16000, unit: "per-traveller" },
      { id: "kids-naturalist", name: "Kids' naturalist programme", description: "A dedicated naturalist for under-12s at Periyar and on the backwaters.", price: 18000, unit: "per-booking" },
      { id: "athirappilly", name: "Athirappilly falls day", description: "A day trip to the Chalakudy river falls with a rainforest walk.", price: 12500, unit: "per-booking" },
    ],
    seasonality: SEASON.indiaWinter,
    groupSizeMax: 10,
    physicality: "Gentle",
  },
  {
    slug: "bali-island-chapters",
    name: "Bali & Nusa Penida — Island Chapters",
    tagline: "Rice terrace, volcano rim, and a limestone island offshore",
    destination: "Bali",
    country: "Indonesia",
    region: "southeast-asia",
    tripTypes: ["honeymoon", "family", "adventure"],
    nights: 7,
    baseAdultINR: 142000,
    fixedPerTravellerINR: 26000,
    rating: 4.6,
    reviewCount: 203,
    hero: photo("1537996194471-e657df975ab4", 2000),
    gallery: [
      { src: photo("1537996194471-e657df975ab4", 1200), caption: "Sidemen valley, early rain" },
      { src: photo("1528181304800-259b08848526", 1200), caption: "Temple gate, Ubud" },
      { src: photo("1518548419970-58e3b4079ab2", 1200), caption: "Kelingking, Nusa Penida" },
      { src: photo("1552465011-b4e21bf6e79a", 1200), caption: "Boat channel at dawn" },
    ],
    summary:
      "Bali structured as three distinct chapters — the Sidemen valley rather than crowded Ubud, two nights on the Batur caldera rim, and three on Nusa Penida's limestone cliffs — with a private boat rather than the public fast ferry.",
    editorsNote:
      "We stopped selling central Ubud in 2023. Sidemen is what Ubud was, forty minutes further east and about a tenth as busy.",
    highlights: [
      "Sidemen valley rice terraces with the working irrigation subak explained",
      "Sunrise from the Batur rim without the 2am trekking convoy",
      "Private boat to Nusa Penida — no fast-ferry scrum",
      "Manta Point at first light, before the day boats arrive",
    ],
    itinerary: [
      { day: 1, title: "Arrival, east", place: "Sidemen", description: "Met at Denpasar and driven ninety minutes east into the Sidemen valley, past Klungkung. Evening on the terrace as the valley fills with cloud.", stay: "Sidemen valley villa", meals: ["Dinner"] },
      { day: 2, title: "Subak and salt", place: "Sidemen", description: "Morning walking the rice terraces with a farmer explaining the thousand-year-old subak water system; afternoon at the Kusamba black-sand salt pans.", stay: "Sidemen valley villa", meals: ["Breakfast", "Lunch"], highlight: "Walking the subak with the farmer who actually manages that water share." },
      { day: 3, title: "Besakih and up to the rim", place: "Kintamani", description: "The mother temple at Besakih early, then the climb to the Batur caldera. Hot springs on the lake shore in the afternoon.", stay: "Batur rim lodge", meals: ["Breakfast", "Dinner"] },
      { day: 4, title: "Volcano morning", place: "Kintamani", description: "Sunrise from your own terrace on the rim, then a coffee estate and a Balinese cooking class in the highlands.", stay: "Batur rim lodge", meals: ["Breakfast", "Lunch", "Dinner"] },
      { day: 5, title: "Crossing to Penida", place: "Nusa Penida", description: "Down to Sanur and across by private boat. Afternoon at Kelingking with the cliff to yourselves by 4pm.", stay: "Nusa Penida cliff villa", meals: ["Breakfast", "Dinner"] },
      { day: 6, title: "Manta Point at first light", place: "Nusa Penida", description: "On the water at 6:30 for the manta cleaning stations, then Crystal Bay and Angel's Billabong on the falling tide.", stay: "Nusa Penida cliff villa", meals: ["Breakfast", "Lunch", "Dinner"], highlight: "First boat on the water at Manta Point, an hour ahead of the day trips." },
      { day: 7, title: "Penida, unstructured", place: "Nusa Penida", description: "Deliberately empty. Diamond Beach, the west coast, or nothing at all.", stay: "Nusa Penida cliff villa", meals: ["Breakfast", "Dinner"] },
      { day: 8, title: "Depart", place: "Denpasar", description: "Private boat back to Sanur and on to the airport.", stay: "—", meals: ["Breakfast"] },
    ],
    inclusions: [
      "7 nights across valley villa, caldera lodge and cliff villa",
      "Private driver and vehicle for all Bali land transfers",
      "Private boat crossings to and from Nusa Penida",
      "English-speaking guide on all scheduled excursions",
      "Daily breakfast plus meals as listed",
    ],
    exclusions: [
      "International flights to Denpasar",
      "Indonesian visa on arrival",
      "Scuba diving (snorkelling included)",
      "Temple donations and sarong hire",
    ],
    route: [
      { name: "Denpasar", x: 34, y: 82, nights: 0, arriveDay: 1 },
      { name: "Sidemen", x: 62, y: 54, nights: 2, arriveDay: 1 },
      { name: "Kintamani", x: 52, y: 26, nights: 2, arriveDay: 3 },
      { name: "Nusa Penida", x: 76, y: 90, nights: 3, arriveDay: 5 },
    ],
    rooms: [
      { id: "garden-villa", name: "One-Bedroom Villa", description: "Private pool villa at each of the three properties.", multiplier: 1, maxAdults: 2 },
      { id: "valley-villa", name: "Valley-Edge Villa", description: "Infinity edge over the Sidemen valley and the Penida cliff line.", multiplier: 1.3, maxAdults: 2 },
      { id: "two-bed", name: "Two-Bedroom Villa", description: "Two bedrooms and a shared living pavilion — for families or two couples.", multiplier: 1.68, maxAdults: 4 },
    ],
    addOns: [
      { id: "surf", name: "Surf coaching, three sessions", description: "Private coaching at Balangan or Keramas depending on swell.", price: 24000, unit: "per-traveller" },
      { id: "penida-dive", name: "Two-tank dive at Manta Point", description: "For certified divers — Manta Point and Crystal Bay with a private guide.", price: 19000, unit: "per-traveller", recommended: true },
      { id: "wedding-blessing", name: "Balinese blessing ceremony", description: "A traditional melukat purification at a water temple with a pemangku.", price: 42000, unit: "per-booking" },
      { id: "photographer-bali", name: "Half-day photographer", description: "A four-hour shoot across Sidemen or the Penida cliffs.", price: 38000, unit: "per-booking" },
    ],
    seasonality: SEASON.archipelago,
    groupSizeMax: 10,
    physicality: "Moderate",
  },
  {
    slug: "oman-sands-and-wadis",
    name: "Oman — Sands, Wadis & the Empty Quarter",
    tagline: "Muscat, the Hajar mountains and a night on the Wahiba edge",
    destination: "Oman",
    country: "Oman",
    region: "arabia",
    tripTypes: ["adventure", "corporate", "culture"],
    nights: 6,
    baseAdultINR: 176000,
    fixedPerTravellerINR: 32000,
    rating: 4.7,
    reviewCount: 47,
    hero: photo("1547471080-7cc2caa01a7e", 2000),
    gallery: [
      { src: photo("1547471080-7cc2caa01a7e", 1200), caption: "Wahiba Sands, late light" },
      { src: photo("1512453979798-5ea266f8880c", 1200), caption: "Muttrah corniche" },
      { src: photo("1518684079-3c830dcef090", 1200), caption: "Hajar switchbacks" },
      { src: photo("1523805009345-7448845a9e53", 1200), caption: "Wadi pool, Bani Khalid" },
    ],
    summary:
      "Six nights of genuine desert and mountain — Muttrah's souq, the Jebel Akhdar terraces at 2,000m, a wadi swim between limestone walls, and one night on the edge of the Wahiba with a Bedouin family.",
    editorsNote:
      "This is the one we send corporate groups on. The 4x4 dune driving and the wadi day do more for a leadership team in two days than a hotel ballroom does in five.",
    highlights: [
      "Jebel Akhdar's rose terraces and the abandoned village of Wadi Bani Habib",
      "A wadi swim at Bani Khalid before the day crowd arrives",
      "Desert night with a Bedouin family, not a themed camp",
      "Turtle watch at Ras al Jinz under red light with a reserve biologist",
    ],
    itinerary: [
      { day: 1, title: "Muscat, low key", place: "Muscat", description: "Arrive and settle. Evening on the Muttrah corniche and through the souq as the fishing boats come in.", stay: "Muscat harbour hotel", meals: ["Dinner"] },
      { day: 2, title: "Mosque, museum, coast", place: "Muscat", description: "The Sultan Qaboos Grand Mosque at opening, the National Museum, then the Bandar Khayran coast by dhow.", stay: "Muscat harbour hotel", meals: ["Breakfast", "Lunch"] },
      { day: 3, title: "Up Jebel Akhdar", place: "Jebel Akhdar", description: "The 4x4-only ascent to 2,000m. Afternoon walking the terrace villages of Al Ayn, Sayq and Wadi Bani Habib.", stay: "Alila Jabal Akhdar", meals: ["Breakfast", "Dinner"], highlight: "The terrace walk between three villages, with a falaj-keeper explaining the water rota." },
      { day: 4, title: "Nizwa and down", place: "Nizwa", description: "Nizwa fort and the goat market if it is a Friday, then Bahla and Jabrin on the way east.", stay: "Nizwa heritage inn", meals: ["Breakfast", "Lunch"] },
      { day: 5, title: "Wadi, then dunes", place: "Wahiba Sands", description: "Wadi Bani Khalid in the morning, then tyres down and into the Wahiba by mid-afternoon. Dinner with a Bedouin family; sleep under the dune line.", stay: "Desert camp, private tent", meals: ["Breakfast", "Lunch", "Dinner"], highlight: "Dinner cooked by the family whose grazing land the camp sits on." },
      { day: 6, title: "Turtles at Ras al Jinz", place: "Ras al Jinz", description: "East to the turtle reserve. A biologist-led night walk under red light as the green turtles come ashore to nest.", stay: "Ras al Jinz reserve lodge", meals: ["Breakfast", "Dinner"] },
      { day: 7, title: "Return to Muscat", place: "Muscat", description: "The coastal road back — Sur, the Bimmah sinkhole, and on to the airport.", stay: "—", meals: ["Breakfast"] },
    ],
    inclusions: [
      "6 nights across city hotel, mountain resort, heritage inn, desert camp and reserve lodge",
      "4x4 with a driver-guide throughout, one vehicle per 4 guests",
      "Dune driving with tyre-pressure management and recovery kit",
      "Turtle reserve permits and biologist escort",
      "All meals as listed, including the Bedouin dinner",
    ],
    exclusions: [
      "Flights to and from Muscat",
      "Oman e-visa",
      "Alcohol (limited availability outside Muscat hotels)",
      "Gratuities",
    ],
    route: [
      { name: "Muscat", x: 22, y: 22, nights: 2, arriveDay: 1 },
      { name: "Jebel Akhdar", x: 44, y: 46, nights: 1, arriveDay: 3 },
      { name: "Nizwa", x: 52, y: 58, nights: 1, arriveDay: 4 },
      { name: "Wahiba Sands", x: 72, y: 66, nights: 1, arriveDay: 5 },
      { name: "Ras al Jinz", x: 88, y: 40, nights: 1, arriveDay: 6 },
    ],
    rooms: [
      { id: "standard", name: "Deluxe Room", description: "Standard category across all five properties, including a private desert tent.", multiplier: 1, maxAdults: 2 },
      { id: "cliff-suite", name: "Cliff Suite", description: "Canyon-edge suite at Jebel Akhdar and an upgraded desert tent with a private deck.", multiplier: 1.34, maxAdults: 2 },
      { id: "group-block", name: "Group Block (corporate)", description: "Contiguous room block with a private dining pavilion and a meeting tent in the desert.", multiplier: 1.18, maxAdults: 2 },
    ],
    addOns: [
      { id: "empty-quarter", name: "Empty Quarter extension", description: "Two extra nights into the Rub' al Khali proper, with a navigator and two support vehicles.", price: 118000, unit: "per-traveller" },
      { id: "canyoning", name: "Snake Canyon canyoning", description: "A guided half-day of abseiling and swimming through Wadi Bani Awf.", price: 21000, unit: "per-traveller", recommended: true },
      { id: "facilitator", name: "Corporate facilitator", description: "A leadership facilitator who runs sessions in the wadi and around the desert fire.", price: 165000, unit: "per-booking" },
      { id: "dhow-charter", name: "Private dhow charter", description: "A full-day dhow with a chef along the Bandar Khayran fjords.", price: 88000, unit: "per-booking" },
    ],
    seasonality: SEASON.desertWinter,
    groupSizeMax: 16,
    physicality: "Active",
  },
  {
    slug: "kenya-mara-migration",
    name: "Kenya — The Mara in Migration",
    tagline: "Laikipia, the Mara triangle, and a river crossing if the herd obliges",
    destination: "Maasai Mara & Laikipia",
    country: "Kenya",
    region: "east-africa",
    tripTypes: ["adventure", "family", "wellness"],
    nights: 7,
    baseAdultINR: 386000,
    fixedPerTravellerINR: 58000,
    rating: 4.9,
    reviewCount: 92,
    hero: photo("1516426122078-c23e76319801", 2000),
    gallery: [
      { src: photo("1516426122078-c23e76319801", 1200), caption: "Mara plain, first light" },
      { src: photo("1549366021-9f761d450615", 1200), caption: "The Mara triangle" },
      { src: photo("1547721064-da6cfb341d50", 1200), caption: "Laikipia conservancy" },
      { src: photo("1534177616072-ef7dc120449d", 1200), caption: "Balloon shadow at dawn" },
    ],
    summary:
      "Three nights in a private Laikipia conservancy where walking and night drives are permitted, then four in the Mara triangle — the quiet western third of the reserve — timed against the Mara river crossings.",
    editorsNote:
      "The migration is not a schedule, it is a probability. We put you in the triangle with a guide who reads the herd, and we tell you honestly what the odds are for your dates.",
    highlights: [
      "Laikipia conservancy: walking safaris and night drives, both banned inside the national reserve",
      "Four nights in the Mara triangle, the least-vehicle third of the ecosystem",
      "A guide-to-guest ratio of one vehicle per four, never shared",
      "Optional dawn balloon over the Mara with a champagne landing breakfast",
    ],
    itinerary: [
      { day: 1, title: "Nairobi and north", place: "Laikipia", description: "Met at JKIA and onto a light aircraft to Laikipia. In a vehicle before the afternoon light goes.", stay: "Laikipia conservancy lodge", meals: ["Lunch", "Dinner"] },
      { day: 2, title: "Walking the conservancy", place: "Laikipia", description: "A morning on foot with a Samburu tracker and an armed ranger, then a night drive for aardvark, caracal and the smaller cats.", stay: "Laikipia conservancy lodge", meals: ["Breakfast", "Lunch", "Dinner"], highlight: "On foot with a Samburu tracker — reading spoor rather than driving past it." },
      { day: 3, title: "Rhino and the Ewaso", place: "Laikipia", description: "Time with the conservancy's black rhino monitoring team, then a riverside afternoon along the Ewaso Nyiro.", stay: "Laikipia conservancy lodge", meals: ["Breakfast", "Lunch", "Dinner"] },
      { day: 4, title: "Across to the Mara", place: "Maasai Mara", description: "Light aircraft south-west to the Mara triangle airstrip. An evening drive along the Mara river escarpment.", stay: "Mara triangle tented camp", meals: ["Breakfast", "Lunch", "Dinner"] },
      { day: 5, title: "The river", place: "Maasai Mara", description: "A full day on the crossing points with a packed breakfast and lunch in the vehicle. Patience is the entire technique.", stay: "Mara triangle tented camp", meals: ["Breakfast", "Lunch", "Dinner"], highlight: "A full day held at the crossing points rather than a two-hour drive-by." },
      { day: 6, title: "Predators and the Maasai", place: "Maasai Mara", description: "Dawn with the resident lion prides, then an afternoon in a Maasai enclosure with the family who leases the conservancy land.", stay: "Mara triangle tented camp", meals: ["Breakfast", "Lunch", "Dinner"] },
      { day: 7, title: "Last morning on the plain", place: "Maasai Mara", description: "One more dawn drive. Afternoon at camp, or the balloon if you have added it.", stay: "Mara triangle tented camp", meals: ["Breakfast", "Lunch", "Dinner"] },
      { day: 8, title: "Fly to Nairobi", place: "Nairobi", description: "Morning flight to Wilson, transfer to JKIA with day-room access before evening connections.", stay: "—", meals: ["Breakfast"] },
    ],
    inclusions: [
      "7 nights full board in a conservancy lodge and a Mara triangle tented camp",
      "All internal light-aircraft flights, Nairobi–Laikipia–Mara–Nairobi",
      "Private 4x4 game vehicle and professional guide throughout",
      "All park, conservancy and community fees",
      "House beverages, laundry, and a Nairobi day room on departure",
    ],
    exclusions: [
      "International flights to Nairobi",
      "Kenya eTA",
      "Balloon safari (available as an add-on)",
      "Premium spirits and champagne",
      "Gratuities for guides and camp staff",
    ],
    route: [
      { name: "Nairobi", x: 74, y: 62, nights: 0, arriveDay: 1 },
      { name: "Laikipia", x: 66, y: 24, nights: 3, arriveDay: 1 },
      { name: "Mara Triangle", x: 20, y: 56, nights: 4, arriveDay: 4 },
      { name: "Mara River", x: 30, y: 48, nights: 0, arriveDay: 5 },
    ],
    rooms: [
      { id: "tent", name: "Classic Tent", description: "Canvas suite with an en-suite bathroom and a private veranda onto the plain.", multiplier: 1, maxAdults: 2 },
      { id: "suite-tent", name: "Suite Tent with Plunge", description: "Larger canvas suite with an outdoor shower and a private plunge pool.", multiplier: 1.29, maxAdults: 2 },
      { id: "family-tent", name: "Family Tent", description: "Two bedrooms under one canvas with a shared deck — children over six only.", multiplier: 1.62, maxAdults: 4 },
    ],
    addOns: [
      { id: "balloon", name: "Dawn balloon safari", description: "An hour over the Mara at first light, landing to a bush breakfast.", price: 62000, unit: "per-traveller", recommended: true },
      { id: "photo-vehicle", name: "Photographic vehicle", description: "A converted vehicle with bean bags, a dropped floor and no more than three guests.", price: 96000, unit: "per-booking" },
      { id: "conservation", name: "A day with the anti-poaching unit", description: "Out with the rangers on patrol and at the K9 unit in Laikipia.", price: 34000, unit: "per-traveller" },
      { id: "extra-mara", name: "Extra Mara night", description: "One additional night in the triangle — the single best way to improve crossing odds.", price: 74000, unit: "per-traveller" },
    ],
    seasonality: SEASON.migration,
    groupSizeMax: 8,
    physicality: "Moderate",
  },
  {
    slug: "amalfi-cilento-coast",
    name: "Amalfi & the Cilento Coast",
    tagline: "Ravello, Capri, and the coast most people drive past",
    destination: "Campania",
    country: "Italy",
    region: "mediterranean",
    tripTypes: ["honeymoon", "culture", "family"],
    nights: 8,
    baseAdultINR: 342000,
    fixedPerTravellerINR: 62000,
    rating: 4.8,
    reviewCount: 137,
    hero: photo("1533105079780-92b9be482077", 2000),
    gallery: [
      { src: photo("1533105079780-92b9be482077", 1200), caption: "Positano, from the water" },
      { src: photo("1516483638261-f4dbaf036963", 1200), caption: "Ravello terrace" },
      { src: photo("1531572753322-ad063cecc140", 1200), caption: "Paestum, Temple of Neptune" },
      { src: photo("1523805009345-7448845a9e53", 1200), caption: "Cilento, empty in August" },
    ],
    summary:
      "Eight nights that start high in Ravello, drop to the water for Capri and the Li Galli islands, and then head south into the Cilento — Greek temples at Paestum, buffalo mozzarella at the source, and beaches with nobody on them.",
    editorsNote:
      "The Amalfi coast in August is a traffic jam with a view. The Cilento, forty minutes south, has better swimming and a third of the people. We split the trip across both on purpose.",
    highlights: [
      "A private gozzo along the coast, with a swim stop at the Li Galli islands",
      "Villa Cimbrone's terrace before the gates open to day visitors",
      "Paestum's Greek temples with an archaeologist, at 8am",
      "Buffalo mozzarella made in front of you at a Cilento caseificio",
    ],
    itinerary: [
      { day: 1, title: "Naples to Ravello", place: "Ravello", description: "Met at Capodichino and driven up to Ravello — above the coast road, above the noise. Evening on the terrace.", stay: "Palazzo Avino", meals: ["Dinner"] },
      { day: 2, title: "Ravello's two villas", place: "Ravello", description: "Villa Rufolo and Villa Cimbrone, the latter before opening, then the Sentiero dei Limoni footpath down to Minori for lunch.", stay: "Palazzo Avino", meals: ["Breakfast", "Lunch"], highlight: "The Cimbrone Terrace of Infinity, empty, an hour before public opening." },
      { day: 3, title: "The coast by gozzo", place: "Amalfi Coast", description: "A private wooden gozzo from Amalfi — Furore fjord, the Li Galli islands, Positano from the water, and long swims between.", stay: "Palazzo Avino", meals: ["Breakfast", "Lunch"] },
      { day: 4, title: "Capri, on the right timetable", place: "Capri", description: "Across at 8am before the ferries, the Blue Grotto on a calm tide, Anacapri and the chairlift, back at dusk.", stay: "Palazzo Avino", meals: ["Breakfast", "Dinner"] },
      { day: 5, title: "South into the Cilento", place: "Paestum", description: "Down past Salerno into a different Italy. Afternoon at a buffalo dairy, then the beach at Licinella.", stay: "Cilento masseria", meals: ["Breakfast", "Lunch", "Dinner"] },
      { day: 6, title: "Paestum at eight", place: "Paestum", description: "Three Greek temples with an archaeologist before the heat, then the Tomb of the Diver in the museum.", stay: "Cilento masseria", meals: ["Breakfast", "Dinner"], highlight: "The temples with an archaeologist, two hours before the coaches." },
      { day: 7, title: "Palinuro and the sea caves", place: "Cilento", description: "By boat around Cape Palinuro through the blue and blood caves, with a long lunch at Marina di Camerota.", stay: "Cilento masseria", meals: ["Breakfast", "Lunch"] },
      { day: 8, title: "Cooking, and nothing else", place: "Cilento", description: "A morning in the masseria kitchen — pasta, the mozzarella you watched being made, a fig tart. Afternoon at the pool.", stay: "Cilento masseria", meals: ["Breakfast", "Lunch", "Dinner"] },
      { day: 9, title: "Depart Naples", place: "Naples", description: "Two hours north to Capodichino, or the high-speed train from Salerno to Rome.", stay: "—", meals: ["Breakfast"] },
    ],
    inclusions: [
      "8 nights across a Ravello palazzo and a Cilento masseria",
      "Private driver and vehicle for all coastal and southern transfers",
      "Full-day private gozzo on the Amalfi coast and the Palinuro cave boat",
      "Archaeologist at Paestum, art historian in Ravello",
      "Daily breakfast plus meals as listed",
    ],
    exclusions: [
      "International flights to Naples",
      "Capri ferry tickets and Blue Grotto entry",
      "Lunches and dinners not listed",
      "City taxes, payable locally",
    ],
    route: [
      { name: "Naples", x: 20, y: 14, nights: 0, arriveDay: 1 },
      { name: "Ravello", x: 40, y: 34, nights: 4, arriveDay: 1 },
      { name: "Capri", x: 12, y: 42, nights: 0, arriveDay: 4 },
      { name: "Paestum", x: 62, y: 62, nights: 4, arriveDay: 5 },
      { name: "Palinuro", x: 84, y: 88, nights: 0, arriveDay: 7 },
    ],
    rooms: [
      { id: "classic", name: "Classic Double", description: "Sea-view rooms in Ravello, garden rooms at the masseria.", multiplier: 1, maxAdults: 2 },
      { id: "terrace-suite", name: "Terrace Suite", description: "Private terrace over the gulf in Ravello, and a masseria suite with its own courtyard.", multiplier: 1.42, maxAdults: 3 },
      { id: "masseria-house", name: "Private Masseria House", description: "The whole two-bedroom stone house at the masseria with a private pool.", multiplier: 1.88, maxAdults: 4 },
    ],
    addOns: [
      { id: "vesuvius", name: "Pompeii & Vesuvius day", description: "Pompeii with an archaeologist at opening, then the crater rim in the afternoon.", price: 44000, unit: "per-booking", recommended: true },
      { id: "wine", name: "Campania wine day", description: "Three estates on Vesuvius and in Irpinia — Lacryma Christi, Fiano, Taurasi.", price: 32000, unit: "per-traveller" },
      { id: "vespa", name: "Vintage Vespa morning", description: "Restored Vespas and a lead rider through the Cilento hill villages.", price: 26000, unit: "per-traveller" },
      { id: "anniversary", name: "Terrace dinner for two", description: "A private table on the Palazzo Avino terrace, chef's menu, gulf below.", price: 68000, unit: "per-booking" },
    ],
    seasonality: SEASON.mediterranean,
    groupSizeMax: 12,
    physicality: "Moderate",
  },
  {
    slug: "peru-sacred-valley",
    name: "Peru — Sacred Valley to Machu Picchu",
    tagline: "Cusco, the valley floor, and the Inca Trail's last two days",
    destination: "Cusco & the Sacred Valley",
    country: "Peru",
    region: "south-america",
    tripTypes: ["adventure", "culture", "family"],
    nights: 9,
    baseAdultINR: 358000,
    fixedPerTravellerINR: 96000,
    rating: 4.8,
    reviewCount: 74,
    hero: photo("1587595431973-160d0d94add1", 2000),
    gallery: [
      { src: photo("1587595431973-160d0d94add1", 1200), caption: "Machu Picchu, before the gate opens" },
      { src: photo("1526392060635-9d6019884377", 1200), caption: "Sacred Valley terraces" },
      { src: photo("1531065208531-4036c0dba3ca", 1200), caption: "Andean ridge, Lares" },
      { src: photo("1518105779142-d975f22f1b0a", 1200), caption: "Cusco rooftops" },
    ],
    summary:
      "Nine nights that acclimatise in the valley before Cusco — the correct order, which almost nobody does — take the Inca Trail's final two days on foot, and enter Machu Picchu through the Sun Gate rather than the bus gate.",
    editorsNote:
      "Cusco is 600m higher than the Sacred Valley. Sleeping low first and climbing later is why our travellers don't lose their third day to altitude.",
    highlights: [
      "The two-day Inca Trail, arriving through Inti Punku at sunrise",
      "Maras salt pans and the Moray terraces with an agronomist",
      "A weaving cooperative in Chinchero, working from raw fleece",
      "Cusco's San Pedro market at 6am with a chef",
    ],
    itinerary: [
      { day: 1, title: "Lima, one night", place: "Lima", description: "Arrive late into Lima and stay in Miraflores. If you land early, a walk along the Malecón.", stay: "Miraflores hotel", meals: [] },
      { day: 2, title: "Fly to Cusco, drive down", place: "Sacred Valley", description: "Morning flight to Cusco, then straight down to the valley at 2,800m — 600m lower and far kinder on arrival day.", stay: "Sacred Valley lodge", meals: ["Breakfast", "Lunch", "Dinner"], highlight: "Descending to the valley on arrival day rather than sleeping high in Cusco." },
      { day: 3, title: "Moray, Maras, Chinchero", place: "Sacred Valley", description: "The circular Inca agricultural terraces at Moray with an agronomist, the salt pans at Maras, and a weaving cooperative at Chinchero.", stay: "Sacred Valley lodge", meals: ["Breakfast", "Lunch"] },
      { day: 4, title: "Pisac and Ollantaytambo", place: "Sacred Valley", description: "The Pisac ruins from above, down through the market, and the fortress terraces at Ollantaytambo in the afternoon light.", stay: "Sacred Valley lodge", meals: ["Breakfast", "Dinner"] },
      { day: 5, title: "Onto the trail — KM104", place: "Inca Trail", description: "The train to KM104 and the climb past Chachabamba to Wiñay Wayna. Six hours, 700m of ascent, and the trail almost to yourselves after 2pm.", stay: "Aguas Calientes hotel", meals: ["Breakfast", "Lunch", "Dinner"] },
      { day: 6, title: "Through the Sun Gate", place: "Machu Picchu", description: "A 5am start back up to Inti Punku for the first light on the citadel, then a full guided circuit before the day trains arrive.", stay: "Aguas Calientes hotel", meals: ["Breakfast", "Dinner"], highlight: "Entering through Inti Punku at sunrise, on foot, ahead of the bus queue." },
      { day: 7, title: "Second look, then Cusco", place: "Cusco", description: "An optional second entry for Huayna Picchu, then the train and transfer up to Cusco at 3,400m.", stay: "Cusco convent hotel", meals: ["Breakfast", "Dinner"] },
      { day: 8, title: "Cusco from the inside", place: "Cusco", description: "San Pedro market at 6am with a chef, Qorikancha and the cathedral, then Sacsayhuamán above the city at dusk.", stay: "Cusco convent hotel", meals: ["Breakfast", "Lunch"] },
      { day: 9, title: "A day you choose", place: "Cusco", description: "Rainbow Mountain, the South Valley churches, a cooking class, or nothing. Your guide holds all four options open.", stay: "Cusco convent hotel", meals: ["Breakfast"] },
      { day: 10, title: "Depart via Lima", place: "Lima", description: "Morning flight to Lima and international connections from the evening.", stay: "—", meals: ["Breakfast"] },
    ],
    inclusions: [
      "9 nights across Lima, a valley lodge, Aguas Calientes and a Cusco convent hotel",
      "Domestic flights Lima–Cusco–Lima",
      "KM104 Inca Trail permit, porter and licensed trail guide",
      "Two Machu Picchu entries and all Vistadome rail tickets",
      "Boleto Turístico covering the valley and Cusco sites",
    ],
    exclusions: [
      "International flights to Lima",
      "Huayna Picchu supplement (limited permits — book early)",
      "Meals not listed, and all alcohol",
      "Trekking equipment hire",
      "Gratuities for guides and porters",
    ],
    route: [
      { name: "Lima", x: 10, y: 30, nights: 1, arriveDay: 1 },
      { name: "Sacred Valley", x: 52, y: 44, nights: 3, arriveDay: 2 },
      { name: "Inca Trail KM104", x: 68, y: 58, nights: 0, arriveDay: 5 },
      { name: "Machu Picchu", x: 78, y: 68, nights: 2, arriveDay: 5 },
      { name: "Cusco", x: 60, y: 30, nights: 3, arriveDay: 7 },
    ],
    rooms: [
      { id: "double", name: "Deluxe Double", description: "Standard category throughout, including the convent hotel's cloister rooms.", multiplier: 1, maxAdults: 2 },
      { id: "suite", name: "Junior Suite", description: "Upgraded rooms with terraces in the valley and a fireplace in Cusco.", multiplier: 1.31, maxAdults: 3 },
      { id: "family-connect", name: "Connecting Family Rooms", description: "Two connecting rooms at every property, with a second guide on the trail day.", multiplier: 1.66, maxAdults: 4 },
    ],
    addOns: [
      { id: "huayna", name: "Huayna Picchu permit", description: "The steep peak above the citadel — 400 permits a day, booked months ahead.", price: 9500, unit: "per-traveller", recommended: true },
      { id: "rainbow", name: "Vinicunca (Rainbow Mountain)", description: "A full day to 5,000m with an early start and a horse on standby.", price: 18000, unit: "per-traveller" },
      { id: "titicaca", name: "Lake Titicaca extension", description: "Three nights on the Peruvian side, including a night on Amantaní with a host family.", price: 124000, unit: "per-traveller" },
      { id: "private-dinner", name: "Valley chef's table", description: "A private dinner at the lodge built around Andean tubers and river trout.", price: 46000, unit: "per-booking" },
    ],
    seasonality: SEASON.andes,
    groupSizeMax: 10,
    physicality: "Active",
  },
];
